version: '3'

services:
  jenkins:
    image: jenkins/jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
    ports:
      - 8100:8080
      - 51000:50000
  jenkins_agent:
    image: alexanderefimov/jenkins_slave:latest
    environment:
      - "JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6uesJAq5l5xNhN/3NOJ27zEwKrOyzFlOuC0UX/FCFQEjjCWm39Qv1cbWnuyazIf0EgQC3R0cj/bPPVSJw1XPicAc+CjBgy2rkZekguPhPbFq2uL82tzc1yuwtvXZ9c3n3b5cRl6oqg9cOXB6d4VolQ4Y5S0RJZWdoefuyWySTKAV42+r/EyTz7kcSu8nZk32+VKNUyGu1TwM0gk0Z+ieYkeTOUkGt6qIKyyqNhtEh+gKO2NKOoPtsdpusRZaJKvYKUhnn+d+jzyj2DxJzj0lc685oPRJHpVjdotEdI3+D/lqOKkLR9BSeCRo8qpYwA9O86HHYaG/TYJIl9E3crkD1 user@localhost.localdomain"
    
volumes:
  jenkins-data:
