---

- name: Deploy web app to servers
  hosts: all
  become: yes

  roles:
    - docker

  tasks:
  - name: Build image
    docker_image:
      path: /home/ec2-user/Dockerfile
      name: nginx
      tag: load_balancer
    
